import type { Req, Route } from '../types.ts';
import { UserError } from '../types.ts';
import { html, fmt, postForm, postBtn, prioBadge, type Safe } from '../ui.ts';
import { render, redirect, okFlash, uuid } from './_page.ts';
import { NA } from '../../core/enrichment.ts';
import { startOfBerlinDay } from '../../core/time.ts';
import { filterFromForm, type StatsFilter } from '../../team/service.ts';
import { ASSIGNMENT_STATUS_LABEL, CHANNEL_LABEL, CONTACT_STATUS_LABEL, HANDOFF_LABEL, METRICS, PLAYBOOKS, ROLES, ROLE_LABEL, STAFF_STATUSES, STAFF_STATUS_LABEL, resultIcon, resultLabel } from '../../team/rules.ts';

const id = uuid.source;
const wrap = async <T>(f: () => Promise<T>): Promise<T> => { try { return await f(); } catch (e) { throw new UserError(e instanceof Error ? e.message : String(e)); } };
const RANGES: [string, string][] = [['today', 'Heute'], ['week', 'Diese Woche'], ['month', 'Dieser Monat'], ['custom', 'Zeitraum']];
const ICONS: Record<string, string> = { PHONE: '📞 Anruf', EMAIL: '✉️ E-Mail' };

/** Zeitraum aus `range` (today|week|month|custom mit from/to). */
export function periodOf(url: URL, now: Date): { range: string; from: Date; to: Date } {
  const range = RANGES.some(([k]) => k === url.searchParams.get('range')) ? url.searchParams.get('range')! : 'today'; const day = startOfBerlinDay(now); const berlin = new Date(now.toLocaleString('en-US', { timeZone: 'Europe/Berlin' }));
  const next = new Date(day.getTime() + 86400000);
  if (range === 'week') return { range, from: new Date(day.getTime() - ((berlin.getDay() + 6) % 7) * 86400000), to: next };
  if (range === 'month') return { range, from: new Date(day.getTime() - (berlin.getDate() - 1) * 86400000), to: next };
  if (range === 'custom') { const f = url.searchParams.get('from'), t = url.searchParams.get('to'); const fd = f && /^\d{4}-\d{2}-\d{2}$/.test(f) ? startOfBerlinDay(new Date(f + 'T12:00:00Z')) : day; const td = t && /^\d{4}-\d{2}-\d{2}$/.test(t) ? new Date(startOfBerlinDay(new Date(t + 'T12:00:00Z')).getTime() + 86400000) : next; return { range, from: fd, to: td }; }
  return { range: 'today', from: day, to: next };
}
const FILTER_KEYS = ['range', 'from', 'to', 'user', 'industry', 'region', 'campaign', 'playbook', 'channel', 'result', 'leadStatus', 'priority'];
function parseFilter(r: Req): { f: StatsFilter; period: ReturnType<typeof periodOf>; qs: (extra?: Record<string, string>) => string } {
  const g = (k: string) => r.url.searchParams.get(k) || undefined; const period = periodOf(r.url, r.ctx.now());
  const f: StatsFilter = { userId: g('user'), from: period.from, to: period.to, industry: g('industry'), region: g('region'), campaignId: g('campaign'), playbook: g('playbook'), channel: g('channel'), result: g('result'), leadStatus: g('leadStatus'), priority: g('priority') };
  const qs = (extra: Record<string, string> = {}) => { const u = new URLSearchParams(); for (const k of FILTER_KEYS) { const v = r.url.searchParams.get(k); if (v) u.set(k, v); } for (const [k, v] of Object.entries(extra)) { if (v) u.set(k, v); else u.delete(k); } return u.toString(); };
  return { f, period, qs };
}
const pct = (a: number, b: number) => (b ? `${Math.round((a / b) * 100)} %` : '–');

/** Mitarbeiter-Tabelle mit Kennzahlen (jede Zahl führt zu den Leads dahinter). Wird auch in Analytics „Mitarbeiter“ gezeigt. */
export async function teamTable(r: Req, f: StatsFilter, qs: (e?: Record<string, string>) => string, base = '/team/activity'): Promise<Safe> {
  const t = r.ctx.team; const [users, metrics, assigned] = await Promise.all([t.users(), t.metricsFor({ ...f, userId: undefined }), t.assignedStats()]);
  const mById = new Map(metrics.map((m) => [m.user_id ?? 'admin', m])); const aById = new Map(assigned.map((a: any) => [a.user_id, a]));
  const rows = [...users.filter((u: any) => !f.userId || u.id === f.userId).map((u: any) => ({ u, id: u.id as string, name: u.name as string, last: u.last_activity_at })), ...(mById.has('admin') && !f.userId ? [{ u: null, id: 'admin', name: 'Admin / ohne Konto', last: mById.get('admin')!.last_attempt }] : [])];
  const cell = (uid: string, key: string, v: number) => html`<td>${v ? html`<a href="${base}?${qs({ metric: key, user: uid === 'admin' ? '' : uid })}">${v}</a>` : 0}</td>`;
  return html`<div class="scroll"><table class="tbl nowrap"><tr><th>Mitarbeiter</th><th>Zugewiesen</th><th>Neu</th><th>Bearbeitet</th><th>Anrufversuche</th><th>E-Mails</th><th>Erreicht</th><th>Interessiert</th><th>Demos</th><th>Rückrufe</th><th>Übergaben</th><th>Erledigt</th><th>Letzte Aktivität</th></tr>
    ${rows.map(({ u, id: uid, name, last }) => { const m = mById.get(uid) ?? {}; const a: any = aById.get(uid) ?? {}; return html`<tr><td>${u ? html`<a href="/team/${uid}"><b>${name}</b></a> <small class="mute">${ROLE_LABEL[u.role as keyof typeof ROLE_LABEL]}${u.status !== 'ACTIVE' ? ` · ${STAFF_STATUS_LABEL[u.status as keyof typeof STAFF_STATUS_LABEL]}` : ''}</small>` : name}</td>
      <td>${a.assigned ?? 0}</td><td>${a.fresh ?? 0}</td><td>${m.worked_leads ?? 0}</td>${cell(uid, 'calls', m.calls ?? 0)}${cell(uid, 'emails', m.emails ?? 0)}${cell(uid, 'reached', m.reached ?? 0)}${cell(uid, 'interested', m.interested ?? 0)}${cell(uid, 'demos', m.demos ?? 0)}${cell(uid, 'callbacks', m.callbacks ?? 0)}${cell(uid, 'handoffs', m.handoffs ?? 0)}<td>${a.finished ?? 0}</td><td>${last ? fmt(last) : 'noch keine'}</td></tr>`; })}</table></div>`;
}
const filterForm = (r: Req, users: any[], camps: any[], f: ReturnType<typeof parseFilter>, action: string, extra: Safe | '' = '') => {
  const v = (k: string) => r.url.searchParams.get(k) ?? ''; const sel = (name: string, label: string, opts: [string, string][]) => html`<label>${label}<select name="${name}"><option value="">alle</option>${opts.map(([k, l]) => html`<option value="${k}" ${v(name) === k ? 'selected' : ''}>${l}</option>`)}</select></label>`;
  return html`<form class="card" method="get" action="${action}">${extra}<div class="row chips">${RANGES.map(([k, l]) => html`<label class="btn ${f.period.range === k ? 'primary' : ''}" style="cursor:pointer"><input type="radio" name="range" value="${k}" ${f.period.range === k ? 'checked' : ''} style="display:none">${l}</label>`)}</div>
    <div class="grid2"><label>Von<input type="date" name="from" value="${v('from')}"></label><label>Bis<input type="date" name="to" value="${v('to')}"></label>
    ${sel('user', 'Mitarbeiter', users.map((u) => [u.id, u.name]))}<label>Branche<input name="industry" value="${v('industry')}"></label><label>Region<input name="region" value="${v('region')}"></label>${sel('campaign', 'Kampagne', camps.map((c) => [c.id, c.name]))}${sel('playbook', 'Playbook', PLAYBOOKS.map((p) => [p.id, p.title]))}
    ${sel('channel', 'Kontaktkanal', Object.entries(CHANNEL_LABEL).map(([k, l]) => [k, l]))}${sel('result', 'Gesprächsergebnis', ['NO_ANSWER', 'NO_INTEREST', 'CALL_BACK', 'WEBSITE_INTEREST', 'DEMO_WANTED', 'PARTNER_INTEREST', 'NEEDS_ANALYSIS', 'MULTIPLE_TOPICS', 'OFFER_REQUESTED', 'HANDOFF', 'DO_NOT_CONTACT', 'EMAIL_DRAFT', 'EMAIL_SENT'].map((k) => [k, resultLabel(k)]))}
    ${sel('leadStatus', 'Leadstatus', ['QUALIFIED', 'DEMO_CREATED', 'CONTACTED', 'REPLIED', 'INTERESTED', 'OFFER_SENT', 'IGNORED'].map((k) => [k, k]))}${sel('priority', 'Priorität', ['A', 'B', 'C', 'D'].map((k) => [k, k]))}</div><button class="primary">Anzeigen</button></form>`;
};

export const routes: Route[] = [
  { method: 'GET', path: /^\/team$/, h: async (r) => {
    const fl = parseFilter(r); const [users, camps] = await Promise.all([r.ctx.team.users(), r.ctx.team.campaigns()]); const admin = r.user.role === 'ADMIN';
    return render(r, { title: 'Team', nav: 'team', body: html`<div class="row">${admin ? html`<a class="btn primary" href="/team/new">+ Mitarbeiter anlegen</a>` : ''}<a class="btn" href="/team/assign">Lead-Zuweisung</a><a class="btn" href="/team/campaigns">Kampagnen</a><a class="btn" href="/team/activity">Team-Aktivität</a><a class="btn" href="/team/handoffs">Übergaben</a><a class="btn" href="/team/goals">Tagesziele</a></div>
      ${filterForm(r, users, camps, fl, '/team')}<h2>Aktivität: ${RANGES.find(([k]) => k === fl.period.range)![1]} <small class="mute">(${fmt(fl.period.from)} – ${fmt(new Date(fl.period.to.getTime() - 1))})</small></h2>
      <div class="card">${await teamTable(r, fl.f, fl.qs)}<small class="mute">Es werden konkrete Zahlen gezeigt, keine Bewertung. Jede Zahl führt zu den Leads dahinter. Vergleiche bitte immer mit Branche, Region und Lead-Priorität (unter Team-Aktivität).</small></div>` });
  } },
  { method: 'GET', path: /^\/team\/new$/, h: async (r) => {
    if (r.user.role !== 'ADMIN') throw new UserError('Nur Administratoren legen Mitarbeiter an.');
    return render(r, { title: 'Mitarbeiter anlegen', nav: 'team', body: html`<div class="card">${postForm(r.app.csrf, '/team/new', html`<label>Name<input name="name" required maxlength="120"></label><label>Login (E-Mail oder Kürzel)<input name="login" required maxlength="80" autocomplete="off"></label><label>Startpasswort (mind. 8 Zeichen; wird nur gehasht gespeichert)<input name="password" type="password" required minlength="8" autocomplete="new-password"></label>
      <label>Rolle<select name="role">${ROLES.filter((x) => x !== 'ADMIN').map((x) => html`<option value="${x}">${ROLE_LABEL[x]}</option>`)}<option value="ADMIN">${ROLE_LABEL.ADMIN}</option></select></label><label>Team<input name="team" maxlength="80"></label><label>Branchen (Komma)<input name="industries"></label><label>Regionen (Komma)<input name="regions"></label><label>Bevorzugte Lead-Kategorien (Komma, z. B. A,B)<input name="preferred_categories"></label><button class="primary">Mitarbeiter anlegen</button>`, { style: 'display:block' })}</div>` });
  } },
  { method: 'POST', path: /^\/team\/new$/, h: async (r) => { if (r.user.role !== 'ADMIN') throw new UserError('Nur Administratoren legen Mitarbeiter an.'); const uid = await r.ctx.team.createUser(Object.fromEntries(r.form), r.user).catch((e) => { throw new UserError(e.message); }); return redirect(`/team/${uid}`, okFlash('Mitarbeiter angelegt.')); } },
  { method: 'GET', path: /^\/team\/assign$/, h: async (r) => {
    const users = (await r.ctx.team.users()).filter((u: any) => u.status === 'ACTIVE'); const g = (k: string) => r.url.searchParams.get(k) ?? ''; const f = filterFromForm(Object.fromEntries(r.url.searchParams)); const n = r.url.searchParams.has('preview') ? await r.ctx.team.preview(f) : null; const sel = g('user');
    const fields = html`<div class="grid2"><label>Branche<input name="industry" value="${g('industry')}" placeholder="z. B. Friseur"></label><label>Region / Ort<input name="region" value="${g('region')}" placeholder="z. B. Saarbrücken"></label><label>Radius (km)<input name="radiusKm" type="number" min="1" value="${g('radiusKm')}"></label>
      <label>Priorität (z. B. A,B)<input name="priorities" value="${g('priorities')}"></label><label>Website<select name="website"><option value="">egal</option><option value="none" ${g('website') === 'none' ? 'selected' : ''}>keine</option><option value="weak" ${g('website') === 'weak' ? 'selected' : ''}>keine oder schwach</option></select></label>
      <label>Mindest-Verkaufschance<input name="minOpportunity" type="number" min="0" max="100" value="${g('minOpportunity')}"></label><label>Partnerpotenzial (HIGH,MEDIUM)<input name="partnerPotential" value="${g('partnerPotential')}"></label><label>Kontaktierbarkeit (z. B. READY,PHONE_ONLY)<input name="contactability" value="${g('contactability')}"></label><label>Anzahl<input name="limit" type="number" min="1" max="1000" value="${g('limit') || '50'}"></label></div>`;
    return render(r, { title: 'Lead-Zuweisung', nav: 'team', body: html`<div class="note">Zugewiesen werden nur Leads ohne Besitzer, nicht gesperrt und nicht pausiert. Du entscheidest – es gibt keine automatische Zuweisung (AUTO_RULE ist ausgeschaltet).</div>
      <form class="card" method="get" action="/team/assign"><h2>1 · Filter</h2>${fields}<label>Mitarbeiter (bei mehreren: Round Robin)<select name="user" ${''}>${users.map((u: any) => html`<option value="${u.id}" ${sel === u.id ? 'selected' : ''}>${u.name}</option>`)}</select></label><button name="preview" value="1">Passende Leads zählen</button></form>
      ${n !== null ? html`<div class="card"><h2>2 · Zuweisen</h2><p><b>${n}</b> Lead(s) passen zum Filter.</p>${postForm(r.app.csrf, '/team/assign', html`${[...r.url.searchParams.entries()].filter(([k]) => !['preview', 'user', 'users'].includes(k)).map(([k, v]) => html`<input type="hidden" name="${k}" value="${v}">`)}
        <fieldset><legend>Mitarbeiter wählen (mehrere = Round Robin)</legend>${users.map((u: any) => html`<label class="inline"><input type="checkbox" name="users" value="${u.id}" ${sel === u.id ? 'checked' : ''}> ${u.name}</label>`)}</fieldset><button class="primary" ${n ? '' : 'disabled'}>${Math.min(n, f.limit ?? 50)} Leads zuweisen</button>`, { style: 'display:block' })}</div>` : ''}` });
  } },
  { method: 'POST', path: /^\/team\/assign$/, h: async (r) => {
    const users = r.form.getAll('users'); const out = await wrap(() => r.ctx.team.assignBatch(filterFromForm(Object.fromEntries(r.form)), users, r.user, {}));
    return redirect('/team/assign', okFlash(`${out.assigned} Lead(s) zugewiesen.`)); } },
  { method: 'POST', path: new RegExp(`^/team/leads/${id}/assign$`), h: async (r) => { await wrap(() => r.ctx.team.assignOne(r.params[0], r.form.get('user') ?? '', r.user)); return redirect(`/leads/${r.params[0]}?tab=verlauf#zuweisung`, okFlash('Lead zugewiesen.')); } },
  { method: 'POST', path: new RegExp(`^/team/leads/${id}/unassign$`), h: async (r) => { await r.ctx.team.unassign(r.params[0], r.user, 'RETURNED'); return redirect(`/leads/${r.params[0]}?tab=verlauf#zuweisung`, okFlash('Zuweisung aufgehoben.')); } },
  { method: 'POST', path: new RegExp(`^/team/leads/${id}/unlock$`), h: async (r) => { await r.ctx.team.adminUnlock(r.params[0], r.user); return redirect(r.req.headers.referer ? new URL(r.req.headers.referer).pathname : `/leads/${r.params[0]}`, okFlash('Sperre gelöst.')); } },
  { method: 'GET', path: /^\/team\/campaigns$/, h: async (r) => {
    const [camps, users] = await Promise.all([r.ctx.team.campaigns(), (await r.ctx.team.users()).filter((u: any) => u.status === 'ACTIVE')]);
    return render(r, { title: 'Kampagnen', nav: 'team', body: html`<div class="card">${camps.length ? html`<div class="scroll"><table class="tbl nowrap"><tr><th>Kampagne</th><th>Mitarbeiter</th><th>Zugewiesen</th><th>Bearbeitet</th><th>Offen</th><th>Erreicht</th><th>Interessiert</th><th>Demo</th><th>Übergaben</th></tr>${camps.map((c: any) => html`<tr><td><a href="/team/campaigns/${c.id}"><b>${c.name}</b></a></td><td>${c.assignee_name ?? NA}</td><td>${c.total}</td><td>${c.worked}</td><td>${Math.max(0, c.total - c.worked)}</td><td>${c.reached}</td><td>${c.interested}</td><td>${c.demos}</td><td>${c.handoffs}</td></tr>`)}</table></div>` : html`<p class="mute">Noch keine Kampagnen.</p>`}</div>
      <div class="card"><h2>Kampagne erstellen</h2><p class="mute">Speichert das Arbeitspaket und weist die passenden Leads dem Mitarbeiter zu.</p>${postForm(r.app.csrf, '/team/campaigns', html`<label>Name<input name="name" required maxlength="160" placeholder="Friseure Saarbrücken ohne Website KW41"></label>
        <div class="grid2"><label>Branche<input name="industry"></label><label>Region<input name="region"></label><label>Radius (km)<input name="radiusKm" type="number" min="1"></label><label>Priorität (A,B)<input name="priorities"></label><label>Website<select name="website"><option value="">egal</option><option value="none">keine</option><option value="weak">keine oder schwach</option></select></label><label>Kontaktierbarkeit (z. B. READY)<input name="contactability"></label><label>Lead-Anzahl<input name="limit" type="number" min="1" max="1000" value="50"></label>
        <label>Mitarbeiter<select name="assignee" required>${users.map((u: any) => html`<option value="${u.id}">${u.name}</option>`)}</select></label><label>Playbook<select name="playbook"><option value="">System empfiehlt</option>${PLAYBOOKS.map((p) => html`<option value="${p.id}">${p.title}</option>`)}</select></label></div><button class="primary">Kampagne erstellen und Leads zuweisen</button>`, { style: 'display:block' })}</div>` });
  } },
  { method: 'POST', path: /^\/team\/campaigns$/, h: async (r) => { const out = await wrap(() => r.ctx.team.createCampaign(Object.fromEntries(r.form), r.user)); return redirect(`/team/campaigns/${out.id}`, okFlash(`Kampagne erstellt, ${out.assigned} Lead(s) zugewiesen.`)); } },
  { method: 'GET', path: new RegExp(`^/team/campaigns/${id}$`), h: async (r) => {
    const c = await r.ctx.team.campaign(r.params[0]); if (!c) return render(r, { title: 'Nicht gefunden', nav: 'team', status: 404, body: html`<p>Kampagne nicht gefunden.</p>` });
    const leads = (await r.ctx.repo.pool.query('select id, company_name, city, contact_status, assignment_status from leads where campaign_id = $1 and owner_id = $2 order by company_name limit 300', [c.id, r.ctx.repo.ownerId])).rows;
    return render(r, { title: c.name, nav: 'team', crumbs: [['Startseite', '/'], ['Team', '/team'], ['Kampagnen', '/team/campaigns'], [c.name]], back: ['← Zu den Kampagnen', '/team/campaigns'], body: html`<div class="grid"><div class="kpi"><b>${c.total}</b><span>zugewiesen</span></div><div class="kpi"><b>${c.worked}</b><span>bearbeitet</span></div><div class="kpi"><b>${Math.max(0, c.total - c.worked)}</b><span>offen</span></div><div class="kpi"><b>${c.reached}</b><span>erreicht</span></div><div class="kpi"><b>${c.interested}</b><span>interessiert</span></div><div class="kpi"><b>${c.demos}</b><span>Demo</span></div><div class="kpi"><b>${c.handoffs}</b><span>Übergaben</span></div></div>
      <div class="card"><p>Mitarbeiter: <b>${c.assignee_name ?? NA}</b> · Playbook: <b>${c.playbook ? PLAYBOOKS.find((p) => p.id === c.playbook)?.title : 'System empfiehlt'}</b></p><p class="mute">Regeln: ${Object.entries(c.rules ?? {}).filter(([, v]) => v && (!Array.isArray(v) || v.length)).map(([k, v]) => `${k}: ${v}`).join(' · ') || 'keine'}</p></div>
      <div class="card"><ul class="items">${leads.map((l: any) => html`<li><a href="/leads/${l.id}">${l.company_name}</a> <small>${l.city ?? ''} · ${CONTACT_STATUS_LABEL[l.contact_status as keyof typeof CONTACT_STATUS_LABEL]} · ${ASSIGNMENT_STATUS_LABEL[l.assignment_status]}</small></li>`)}</ul></div>` });
  } },
  { method: 'GET', path: /^\/team\/activity$/, h: async (r) => {
    const fl = parseFilter(r); const t = r.ctx.team; const [users, camps] = await Promise.all([t.users(), t.campaigns()]); const metric = r.url.searchParams.get('metric');
    if (metric && METRICS[metric]) {
      const rows = await t.leadsFor(metric, fl.f);
      return render(r, { title: METRICS[metric].label, nav: 'team', crumbs: [['Startseite', '/'], ['Team', '/team'], ['Team-Aktivität', `/team/activity?${fl.qs({ metric: '' })}`], [METRICS[metric].label]], back: ['← Zur Team-Aktivität', `/team/activity?${fl.qs({ metric: '' })}`], body: html`<p class="mute">${rows.length} Lead(s) hinter dieser Kennzahl.</p>
        <div class="card scroll"><table class="tbl"><tr><th>Firma</th><th>Mitarbeiter</th><th>Kanal</th><th>Ergebnis</th><th>Notiz</th><th>Zeitpunkt</th></tr>${rows.map((l: any) => html`<tr><td><a href="/leads/${l.id}?tab=verlauf">${l.company_name}</a><br><small>${l.city ?? ''}</small></td><td>${l.user_name}</td><td>${CHANNEL_LABEL[l.channel] ?? l.channel}</td><td>${resultIcon(l.result, l.channel)} ${resultLabel(l.result)}</td><td>${l.note ?? '–'}</td><td>${fmt(l.at)}</td></tr>`)}</table></div>` });
    }
    const [ind, pri, pbk, reg] = await Promise.all([t.breakdown(fl.f, 'industry'), t.breakdown(fl.f, 'priority'), t.breakdown(fl.f, 'playbook'), t.breakdown(fl.f, 'region')]);
    const m = await t.metricsFor({ ...fl.f, userId: undefined });
    const fu = (await r.ctx.repo.pool.query(`select l.assigned_to_user_id as uid, count(*) filter (where t.status = 'DONE' and t.done_at >= $2 and t.done_at < $3)::int as done, count(*) filter (where t.status = 'OPEN' and t.due_at < $4)::int as overdue from tasks t join leads l on l.id = t.lead_id where l.owner_id = $1 and l.assigned_to_user_id is not null and not t.for_admin group by 1`, [r.ctx.repo.ownerId, fl.f.from, fl.f.to, r.ctx.now()])).rows; const fuBy = new Map(fu.map((x: any) => [x.uid, x]));
    const brk = (rows: any[], label: string) => html`<div class="card scroll"><h2>Nach ${label}</h2><table class="tbl nowrap"><tr><th>Mitarbeiter</th><th>${label}</th><th>Versuche</th><th>Erreicht</th><th>Interessiert</th></tr>${rows.map((x: any) => html`<tr><td>${x.user_name}</td><td>${x.key}</td><td>${x.attempts}</td><td>${x.reached}</td><td>${x.interested}</td></tr>`)}</table></div>`;
    const recent = (await r.ctx.repo.pool.query(`select a.*, l.company_name from contact_attempts a join leads l on l.id = a.lead_id where a.owner_id = $1 and a.started_at >= $2 and a.started_at < $3 ${fl.f.userId ? 'and a.user_id = $4' : ''} order by a.started_at desc limit 40`, fl.f.userId ? [r.ctx.repo.ownerId, fl.f.from, fl.f.to, fl.f.userId] : [r.ctx.repo.ownerId, fl.f.from, fl.f.to])).rows;
    return render(r, { title: 'Team-Aktivität', nav: 'team', body: html`${filterForm(r, users, camps, fl, '/team/activity')}
      <div class="card"><h2>Mitarbeiter und Kennzahlen</h2>${await teamTable(r, fl.f, fl.qs)}</div>
      <div class="card scroll"><h2>Quoten</h2><table class="tbl nowrap"><tr><th>Mitarbeiter</th><th>Reach Rate</th><th>Interest Rate</th><th>Demo Rate</th><th>Handoff Rate</th><th>Follow-up-Erledigung</th></tr>${m.map((x: any) => { const f2: any = fuBy.get(x.user_id) ?? { done: 0, overdue: 0 }; return html`<tr><td>${x.user_name}</td><td>${pct(x.reached, x.calls)} <small class="mute">(${x.reached}/${x.calls})</small></td><td>${pct(x.interested, x.reached)}</td><td>${pct(x.demos, x.reached)}</td><td>${pct(x.handoffs, x.reached)}</td><td>${pct(f2.done, f2.done + f2.overdue)} <small class="mute">(${f2.done} erledigt, ${f2.overdue} überfällig)</small></td></tr>`; })}</table><small class="mute">Quoten sind keine Rangliste. Mitarbeiter haben unterschiedliche Branchen und Leadqualitäten – siehe Aufschlüsselung unten.</small></div>
      ${brk(ind, 'Branche')}${brk(reg, 'Region')}${brk(pri, 'Priorität')}${brk(pbk, 'Playbook')}
      <div class="card"><h2>Letzte Kontaktversuche</h2><ul class="items">${recent.map((a: any) => html`<li><small>${fmt(a.started_at)} · ${a.user_name}</small><div>${resultIcon(a.result, a.channel)} <b>${CHANNEL_LABEL[a.channel] ?? a.channel}</b> – <a href="/leads/${a.lead_id}?tab=verlauf">${a.company_name}</a>: ${resultLabel(a.result)}${a.status === 'DRAFT' ? ' (Entwurf)' : ''}${a.status === 'SENT' ? ' (versendet)' : ''}</div>${a.note ? html`<div class="note">${a.note}</div>` : ''}</li>`)}</ul></div>` });
  } },
  { method: 'GET', path: /^\/team\/handoffs$/, h: async (r) => {
    const rows = await r.ctx.team.handoffs({}); const admin = r.user.role !== 'SALES';
    return render(r, { title: 'Übergaben', nav: 'team', body: html`<div class="card">${rows.length ? html`<ul class="items">${rows.map((h: any) => html`<li><div class="row"><b class="grow"><a href="/leads/${h.lead_id}?tab=verlauf">${h.company_name}</a></b><span class="badge ${h.status === 'OPEN' ? 'b-warn' : 'b-ok'}">${h.status === 'OPEN' ? 'Offen' : h.status === 'ACCEPTED' ? 'Übernommen' : 'Erledigt'}</span></div>
        <small>${HANDOFF_LABEL[h.reason as keyof typeof HANDOFF_LABEL]} · von ${h.from_name} · ${fmt(h.created_at)}</small><dl class="facts"><dt>Ansprechpartner</dt><dd>${h.contact_person ?? NA}</dd><dt>Letzter Kontakt</dt><dd>${fmt(h.last_contact_at)} (${h.last_result ? resultLabel(h.last_result) : NA})</dd><dt>Interesse</dt><dd>${h.interest ?? NA}</dd><dt>Gewünschter Rückruf</dt><dd>${h.callback_wanted_at ? fmt(h.callback_wanted_at) : NA}</dd><dt>Nächster Schritt</dt><dd>${h.next_step ?? NA}</dd></dl><div class="note">${h.note}</div>
        ${h.handled_note ? html`<small>Vermerk: ${h.handled_note}</small>` : ''}${admin && h.status !== 'DONE' ? postForm(r.app.csrf, `/team/handoffs/${h.id}/${h.status === 'OPEN' ? 'accept' : 'done'}`, html`<input name="note" placeholder="Vermerk (optional)" maxlength="2000"><button class="primary">${h.status === 'OPEN' ? 'Übernehmen' : 'Als erledigt markieren'}</button>`, { style: 'display:block' }) : ''}</li>`)}</ul>` : html`<p class="mute">Keine Übergaben.</p>`}</div>` });
  } },
  { method: 'POST', path: new RegExp(`^/team/handoffs/${id}/(accept|done)$`), h: async (r) => { await wrap(() => r.ctx.team.handleHandoff(r.params[0], r.params[1] === 'accept' ? 'ACCEPTED' : 'DONE', r.form.get('note'), r.user)); return redirect('/team/handoffs', okFlash('Übergabe aktualisiert.')); } },
  { method: 'GET', path: /^\/team\/goals$/, h: async (r) => {
    const users = await r.ctx.team.users();
    return render(r, { title: 'Tagesziele', nav: 'team', body: html`<div class="note">Tagesziele dienen nur der Orientierung. Es werden keine Provisionen oder Vergütungen berechnet.</div>${users.map((u: any) => html`<div class="card"><b>${u.name}</b> <small class="mute">${ROLE_LABEL[u.role as keyof typeof ROLE_LABEL]}</small>${postForm(r.app.csrf, `/team/${u.id}/goals`, html`<div class="grid2"><label>Anrufversuche<input name="goal_calls" type="number" min="0" max="1000" value="${u.goal_calls}"></label><label>Erreichte Kontakte<input name="goal_reached" type="number" min="0" max="1000" value="${u.goal_reached}"></label><label>Qualifizierte Gespräche<input name="goal_qualified" type="number" min="0" max="1000" value="${u.goal_qualified}"></label><label>Follow-ups<input name="goal_followups" type="number" min="0" max="1000" value="${u.goal_followups}"></label></div><button>Speichern</button>`, { style: 'display:block' })}</div>`)}${users.length ? '' : html`<p class="mute">Noch keine Mitarbeiter.</p>`}` });
  } },
  { method: 'GET', path: /^\/team\/audit$/, h: async (r) => {
    const rows = await r.ctx.team.auditList({ limit: 200 });
    return render(r, { title: 'Audit-Protokoll', nav: 'team', body: html`<div class="note">Das Protokoll ist unveränderlich: Einträge können in der Oberfläche weder bearbeitet noch gelöscht werden.</div><div class="card scroll"><table class="tbl nowrap"><tr><th>Zeit</th><th>Wer</th><th>Ereignis</th><th>Lead</th></tr>${rows.map((a: any) => html`<tr><td>${fmt(a.at)}</td><td>${a.user_name} <small class="mute">${a.role ?? ''}</small></td><td>${a.event}</td><td>${a.lead_id ? html`<a href="/leads/${a.lead_id}?tab=verlauf">öffnen</a>` : '–'}</td></tr>`)}</table></div>` });
  } },
  { method: 'POST', path: new RegExp(`^/team/${id}/goals$`), h: async (r) => { await r.ctx.team.setGoals(r.params[0], Object.fromEntries(r.form), r.user); return redirect('/team/goals', okFlash('Ziele gespeichert.')); } },
  { method: 'POST', path: new RegExp(`^/team/${id}/feedback$`), h: async (r) => { await wrap(() => r.ctx.team.addFeedback(r.user, { staffId: r.params[0], text: r.form.get('text') ?? '' })); return redirect(`/team/${r.params[0]}#feedback`, okFlash('Feedback gespeichert.')); } },
  { method: 'POST', path: new RegExp(`^/team/${id}$`), h: async (r) => { if (r.user.role !== 'ADMIN') throw new UserError('Nur Administratoren verwalten Mitarbeiter.'); await wrap(() => r.ctx.team.updateUser(r.params[0], Object.fromEntries(r.form), r.user)); return redirect(`/team/${r.params[0]}`, okFlash('Gespeichert.')); } },
  { method: 'GET', path: new RegExp(`^/team/${id}$`), h: async (r) => {
    const t = r.ctx.team; const u = await t.user(r.params[0]); if (!u) return render(r, { title: 'Nicht gefunden', nav: 'team', status: 404, body: html`<p>Mitarbeiter nicht gefunden.</p>` });
    const now = r.ctx.now(); const day = startOfBerlinDay(now); const wk = new Date(day.getTime() - ((new Date(now.toLocaleString('en-US', { timeZone: 'Europe/Berlin' })).getDay() + 6) % 7) * 86400000);
    const [today, week, prog, ass, attempts, fb, audit] = await Promise.all([t.metricsFor({ userId: u.id, from: day, to: new Date(day.getTime() + 86400000) }), t.metricsFor({ userId: u.id, from: wk, to: new Date(day.getTime() + 86400000) }), t.progress(u.id), t.assignedStats(u.id), t.attemptsForUser(u.id, 15), t.feedbackFor(u.id), t.auditList({ userId: u.id, limit: 15 })]);
    const a0: any = ass[0] ?? {}; const td: any = today[0] ?? {}; const wk0: any = week[0] ?? {}; const admin = r.user.role === 'ADMIN';
    const kp = (n: number, l: string) => html`<div class="kpi"><b>${n}</b><span>${l}</span></div>`;
    return render(r, { title: u.name, nav: 'team', crumbs: [['Startseite', '/'], ['Team', '/team'], [u.name]], back: ['← Zum Team', '/team'], body: html`
      <div class="card"><div class="row"><b class="grow">${u.name}</b><span class="badge">${ROLE_LABEL[u.role as keyof typeof ROLE_LABEL]}</span><span class="badge ${u.status === 'ACTIVE' ? 'b-ok' : 'b-warn'}">${STAFF_STATUS_LABEL[u.status as keyof typeof STAFF_STATUS_LABEL]}</span></div>
        <p class="mute">Login: ${u.login} · aktiv seit ${fmt(u.active_since)} · letzter Login ${u.last_login_at ? fmt(u.last_login_at) : 'noch nie'} · letzte Aktivität ${u.last_activity_at ? fmt(u.last_activity_at) : 'noch keine'}</p></div>
      <div class="card"><h2>Heute</h2><div class="grid">${kp(td.calls ?? 0, 'Anrufe')}${kp(td.reached ?? 0, 'erreicht')}${kp(td.interested ?? 0, 'interessiert')}${kp(td.demos ?? 0, 'Demos')}${kp(td.handoffs ?? 0, 'Übergaben')}${kp(td.callbacks ?? 0, 'Rückrufe')}</div>
        <p class="mute">Ziele heute: Anrufe ${prog.calls}/${prog.goals.calls} · Erreicht ${prog.reached}/${prog.goals.reached} · Qualifiziert ${prog.qualified}/${prog.goals.qualified} · Follow-ups ${prog.followups}/${prog.goals.followups}</p></div>
      <div class="card"><h2>Diese Woche</h2><div class="grid">${kp(wk0.calls ?? 0, 'Anrufe')}${kp(wk0.reached ?? 0, 'erreicht')}${kp(wk0.interested ?? 0, 'interessiert')}${kp(wk0.demos ?? 0, 'Demos')}${kp(wk0.handoffs ?? 0, 'Übergaben')}${kp(wk0.emails ?? 0, 'E-Mails')}</div></div>
      <div class="card"><h2>Zugewiesene Leads</h2><p><b>${a0.assigned ?? 0}</b> zugewiesen · ${a0.fresh ?? 0} neu · ${a0.open_leads ?? 0} offen · ${a0.finished ?? 0} erledigt · ${a0.open_tasks ?? 0} offene Aufgaben (${a0.overdue_tasks ?? 0} überfällig)</p><a class="btn primary" href="/team/${u.id}/leads">Alle zugewiesenen Leads ansehen</a></div>
      <div class="card"><h2>Letzte Kontaktversuche</h2><ul class="items">${attempts.map((a: any) => html`<li><small>${fmt(a.started_at)}</small> ${resultIcon(a.result, a.channel)} <a href="/leads/${a.lead_id}?tab=verlauf">${a.company_name}</a> – ${resultLabel(a.result)}${a.note ? html`<div class="note">${a.note}</div>` : ''}</li>`)}</ul>${attempts.length ? '' : html`<p class="mute">Noch keine.</p>`}</div>
      <div class="card" id="feedback"><h2>Feedback</h2><ul class="items">${fb.map((x: any) => html`<li><small>${fmt(x.created_at)} · ${x.author}</small><div>${x.text}</div></li>`)}</ul>${postForm(r.app.csrf, `/team/${u.id}/feedback`, html`<textarea name="text" rows="2" required maxlength="2000" placeholder="Rückmeldung an den Mitarbeiter"></textarea><button>Feedback speichern</button>`, { style: 'display:block' })}</div>
      ${admin ? html`<div class="card"><h2>Profil bearbeiten</h2>${postForm(r.app.csrf, `/team/${u.id}`, html`<label>Name<input name="name" value="${u.name}" maxlength="120"></label><label>Rolle<select name="role">${ROLES.map((x) => html`<option value="${x}" ${u.role === x ? 'selected' : ''}>${ROLE_LABEL[x]}</option>`)}</select></label><label>Status<select name="status">${STAFF_STATUSES.map((x) => html`<option value="${x}" ${u.status === x ? 'selected' : ''}>${STAFF_STATUS_LABEL[x]}</option>`)}</select></label>
        <label>Team<input name="team" value="${u.team ?? ''}"></label><label>Branchen<input name="industries" value="${(u.industries ?? []).join(', ')}"></label><label>Regionen<input name="regions" value="${(u.regions ?? []).join(', ')}"></label><label>Bevorzugte Kategorien<input name="preferred_categories" value="${(u.preferred_categories ?? []).join(', ')}"></label>
        <label>Notizen (nur Admin)<textarea name="admin_notes" rows="3">${u.admin_notes ?? ''}</textarea></label><label>Neues Passwort (leer = unverändert)<input name="password" type="password" autocomplete="new-password" minlength="8"></label><button class="primary">Speichern</button>`, { style: 'display:block' })}</div>` : ''}
      <div class="card"><h2>Protokoll (Audit)</h2><ul class="items">${audit.map((a: any) => html`<li><small>${fmt(a.at)}</small> ${a.event}</li>`)}</ul></div>` });
  } },
  { method: 'GET', path: new RegExp(`^/team/${id}/leads$`), h: async (r) => {
    const u = await r.ctx.team.user(r.params[0]); if (!u) return render(r, { title: 'Nicht gefunden', nav: 'team', status: 404, body: html`<p>Mitarbeiter nicht gefunden.</p>` });
    const rows = await r.ctx.team.assignedLeads(u.id);
    return render(r, { title: 'Zugewiesene Leads', nav: 'team', crumbs: [['Startseite', '/'], ['Team', '/team'], [u.name, `/team/${u.id}`], ['Zugewiesene Leads']], back: ['← Zu Mitarbeiter', `/team/${u.id}`], body: html`<p class="mute">${u.name}: ${rows.length} zugewiesene Leads.</p><div class="card scroll"><table class="tbl"><tr><th>Firma</th><th>Branche</th><th>Ort</th><th>Zugewiesen am</th><th>Status</th><th>Letzter Kontakt</th><th>Kanal</th><th>Ergebnis</th><th>Notiz</th><th>Nächste Aktion</th><th>Fällig</th></tr>
        ${rows.map((l: any) => html`<tr><td><a href="/leads/${l.id}?tab=verlauf">${l.company_name}</a></td><td>${l.sub_industry ?? NA}</td><td>${l.city ?? NA}</td><td>${fmt(l.assigned_at)}</td><td>${CONTACT_STATUS_LABEL[l.contact_status as keyof typeof CONTACT_STATUS_LABEL]}<br><small>${ASSIGNMENT_STATUS_LABEL[l.assignment_status]}</small></td><td>${l.last_contact_at ? fmt(l.last_contact_at) : '–'}</td><td>${l.channel ? ICONS[l.channel] ?? CHANNEL_LABEL[l.channel] : '–'}</td><td>${l.result ? html`${resultIcon(l.result, l.channel)} ${resultLabel(l.result)}` : '–'}</td><td>${l.note ?? '–'}</td><td>${l.next_step ?? '–'}</td><td>${l.callback_at ? fmt(l.callback_at) : '–'}</td></tr>`)}</table></div>` });
  } },
];
void prioBadge; void postBtn;
